#!/bin/bash

# Prepare disk for MediaWiki data (it formats the disk)
mkfs -t ext4 /dev/vdb

# Update and installation of mysql-server, nova-client and keystone-client packages.
apt-get update
apt-get install -y python-swiftclient apache2 mysql-client php5-mysql php5 libapache2-mod-php5 php5-mcrypt php5-gd imagemagick php5-apcu python-pygments apache2-mpm-prefork php5-readline php5-json php5-cli
apt-get -y clean

# Prepare the disk!
echo "/dev/vdb /var/www/html/wiki/images ext4 defaults 0 0" >> /etc/fstab
